-- Phase 4: Add Domain Resources
-- Adds orders, vision_exams, and inventory tables with role-based RLS policies

-- ============================================================
-- 1. Create updated_at trigger function (generic for all tables)
-- ============================================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- ============================================================
-- 2. Orders table
-- ============================================================
CREATE TABLE "public"."orders" (
  "id" bigint generated by default as identity not null,
  "contact_id" bigint not null references "public"."contacts"("id") on delete cascade,
  "member_id" bigint references "public"."members"("id"),
  "status" text not null default 'new_entry',
  "order_date" timestamp with time zone not null default now(),
  "expected_delivery" timestamp with time zone,
  "arrived_date" timestamp with time zone,
  "completed_date" timestamp with time zone,
  "pickup_date" timestamp with time zone,
  "frame_description" text,
  "lens_details" jsonb default '{}',
  "accessories" jsonb default '[]',
  "total_amount" numeric(10,2),
  "notes" text default '',
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  constraint orders_pkey primary key (id),
  constraint orders_status_check check (status in ('new_entry', 'lens_ordered', 'arrived', 'qa_check', 'in_progress', 'completed', 'notified', 'picked_up'))
);

ALTER TABLE "public"."orders" ENABLE ROW LEVEL SECURITY;

-- Set updated_at trigger
CREATE TRIGGER set_orders_updated_at
BEFORE UPDATE ON public.orders
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- 3. Vision exams table
-- ============================================================
CREATE TABLE "public"."vision_exams" (
  "id" bigint generated by default as identity not null,
  "contact_id" bigint not null references "public"."contacts"("id") on delete cascade,
  "member_id" bigint references "public"."members"("id"),
  "exam_date" timestamp with time zone not null default now(),
  "expires_at" timestamp with time zone,
  "prescription" jsonb default '{}',
  "notes" text default '',
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  constraint vision_exams_pkey primary key (id)
);

ALTER TABLE "public"."vision_exams" ENABLE ROW LEVEL SECURITY;

-- Set updated_at trigger
CREATE TRIGGER set_vision_exams_updated_at
BEFORE UPDATE ON public.vision_exams
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- 4. Inventory table
-- ============================================================
CREATE TABLE "public"."inventory" (
  "id" bigint generated by default as identity not null,
  "name" text not null,
  "category" text not null default 'frame',
  "sku" text,
  "supplier" text,
  "quantity_on_hand" integer not null default 0,
  "reorder_point" integer not null default 5,
  "unit_cost" numeric(10,2),
  "retail_price" numeric(10,2),
  "specifications" jsonb default '{}',
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  constraint inventory_pkey primary key (id),
  constraint inventory_category_check check (category in ('frame', 'lens', 'coating', 'case', 'cloth', 'accessory', 'other'))
);

ALTER TABLE "public"."inventory" ENABLE ROW LEVEL SECURITY;

-- Set updated_at trigger
CREATE TRIGGER set_inventory_updated_at
BEFORE UPDATE ON public.inventory
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- 5. Orders summary view
-- ============================================================
CREATE OR REPLACE VIEW "public"."orders_summary" WITH (security_invoker=off) AS
SELECT
  o.*,
  c.first_name as contact_first_name,
  c.last_name as contact_last_name,
  m.first_name as member_first_name,
  m.last_name as member_last_name
FROM "public"."orders" o
LEFT JOIN "public"."contacts" c ON o.contact_id = c.id
LEFT JOIN "public"."members" m ON o.member_id = m.id;

-- ============================================================
-- 6. Auto-set member_id triggers
-- ============================================================

-- Orders: auto-set member_id to current member
CREATE OR REPLACE FUNCTION public.set_order_member_id_default()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF NEW.member_id IS NULL THEN
    NEW.member_id := (SELECT id FROM public.members WHERE user_id = auth.uid() LIMIT 1);
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER set_order_member_id
BEFORE INSERT ON public.orders
FOR EACH ROW EXECUTE FUNCTION public.set_order_member_id_default();

-- Vision exams: auto-set member_id to current member
CREATE OR REPLACE FUNCTION public.set_vision_exam_member_id_default()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF NEW.member_id IS NULL THEN
    NEW.member_id := (SELECT id FROM public.members WHERE user_id = auth.uid() LIMIT 1);
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER set_vision_exam_member_id
BEFORE INSERT ON public.vision_exams
FOR EACH ROW EXECUTE FUNCTION public.set_vision_exam_member_id_default();

-- ============================================================
-- 7. RLS Policies
-- ============================================================

-- === ORDERS ===

-- SELECT: admin/manager/office see all, salesperson sees own, glazier sees assigned
CREATE POLICY "orders_select" ON "public"."orders"
AS PERMISSIVE FOR SELECT TO authenticated
USING (
  public.get_current_member_role() IN ('admin', 'manager', 'office')
  OR (public.get_current_member_role() = 'salesperson' AND member_id = public.get_current_member_id())
  OR (public.get_current_member_role() = 'glazier' AND status IN ('in_progress', 'qa_check'))
);

-- INSERT: admin/manager/office/salesperson
CREATE POLICY "orders_insert" ON "public"."orders"
AS PERMISSIVE FOR INSERT TO authenticated
WITH CHECK (
  public.get_current_member_role() IN ('admin', 'manager', 'office', 'salesperson')
);

-- UPDATE: admin/manager see all, salesperson own only
CREATE POLICY "orders_update" ON "public"."orders"
AS PERMISSIVE FOR UPDATE TO authenticated
USING (
  public.get_current_member_role() IN ('admin', 'manager')
  OR (public.get_current_member_role() = 'salesperson' AND member_id = public.get_current_member_id())
);

-- DELETE: admin/manager only
CREATE POLICY "orders_delete" ON "public"."orders"
AS PERMISSIVE FOR DELETE TO authenticated
USING (
  public.get_current_member_role() IN ('admin', 'manager')
);

-- === VISION EXAMS ===

-- SELECT: all authenticated (everyone needs to see prescriptions)
CREATE POLICY "vision_exams_select" ON "public"."vision_exams"
AS PERMISSIVE FOR SELECT TO authenticated
USING (true);

-- INSERT: admin/manager/salesperson
CREATE POLICY "vision_exams_insert" ON "public"."vision_exams"
AS PERMISSIVE FOR INSERT TO authenticated
WITH CHECK (
  public.get_current_member_role() IN ('admin', 'manager', 'salesperson')
);

-- UPDATE: admin/manager, salesperson own only
CREATE POLICY "vision_exams_update" ON "public"."vision_exams"
AS PERMISSIVE FOR UPDATE TO authenticated
USING (
  public.get_current_member_role() IN ('admin', 'manager')
  OR (public.get_current_member_role() = 'salesperson' AND member_id = public.get_current_member_id())
);

-- DELETE: admin/manager only
CREATE POLICY "vision_exams_delete" ON "public"."vision_exams"
AS PERMISSIVE FOR DELETE TO authenticated
USING (
  public.get_current_member_role() IN ('admin', 'manager')
);

-- === INVENTORY ===

-- SELECT: all authenticated (everyone can browse)
CREATE POLICY "inventory_select" ON "public"."inventory"
AS PERMISSIVE FOR SELECT TO authenticated
USING (true);

-- INSERT: admin/manager/glazier
CREATE POLICY "inventory_insert" ON "public"."inventory"
AS PERMISSIVE FOR INSERT TO authenticated
WITH CHECK (
  public.get_current_member_role() IN ('admin', 'manager', 'glazier')
);

-- UPDATE: admin/manager/glazier
CREATE POLICY "inventory_update" ON "public"."inventory"
AS PERMISSIVE FOR UPDATE TO authenticated
USING (
  public.get_current_member_role() IN ('admin', 'manager', 'glazier')
);

-- DELETE: admin/manager only
CREATE POLICY "inventory_delete" ON "public"."inventory"
AS PERMISSIVE FOR DELETE TO authenticated
USING (
  public.get_current_member_role() IN ('admin', 'manager')
);
