-- ================================================
-- Phase 5: Agent Integration — user_state table
-- Tracks where each user is navigating in the app
-- Agent queries this table to know user context
-- ================================================

CREATE TABLE public.user_state (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  member_id bigint REFERENCES members(id) ON DELETE SET NULL,
  current_path text NOT NULL DEFAULT '/',
  current_resource text,
  current_record_id bigint,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_state_user_id_unique UNIQUE (user_id)
);

-- Index for fast lookups by user
CREATE INDEX user_state_member_id_idx ON user_state(member_id);

-- RLS: users can read/write their own state
ALTER TABLE user_state ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_read_own_state" ON user_state
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "users_upsert_own_state" ON user_state
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "users_update_own_state" ON user_state
  FOR UPDATE USING (auth.uid() = user_id);

-- Allow service role (agent) to read all user states
-- (service role bypasses RLS by default, but this documents intent)

-- Enable Realtime publication (for future app-side subscriptions)
ALTER PUBLICATION supabase_realtime ADD TABLE user_state;

COMMENT ON TABLE user_state IS 'Tracks user navigation state for agent context awareness. One row per user, upserted on route change.';
